### ISSUE TITLE
License is missing for the project.

### ISSUE THREAD

**Issue by tomuxmon** [OmniGUI/OmniGUI#6]
If I understand it correctly nobody can use your code without your permission when you do not have a specific license attached (see [no license](https://choosealicense.com/no-license/)).
Are you planning to change licensing or is it staying that way?

**Comment by SuperJMN** [comment]
There you are!  License added :) Are you interested in using the code?

**Comment by tomuxmon** [comment]
I am just being curious. Since you have added the license I will now close the issue. I will definitely play with it when I have time. Thanks.
